version = 0
commit_goodlist = []

[authorization.lyuk98]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 270C B11B 1189 E79A 17DC  B783 1BDA FDC5 D60E 735C
Comment: Younguk Lee <pr@lyuk98.com>
Comment: pr@lyuk98.com <pr@lyuk98.com>
Comment: 이영욱 <pr@lyuk98.com>

xjMEZJUAJhYJKwYBBAHaRw8BAQdArSPTuRpHzEzPnXqyK+T9YNrFbHUTKlVPTR/F
u0lo8B/NG1lvdW5ndWsgTGVlIDxwckBseXVrOTguY29tPsKOBBMWCgA2FiEEJwyx
GxGJ55oX3LeDG9r9xdYOc1wFAmmynPMCGwMECwkIBwQVCgkIBRYCAwEAAh4BAheA
AAoJEBva/cXWDnNccRoBAL7Nu/E7HsPcz7Y8Rr4ov83H0VY+KHHHcizZ4DeCxuEC
AQCbtCRtVTYZYYaePBguaX97V47VGPJGeWgMAszKXqMYCc0dcHJAbHl1azk4LmNv
bSA8cHJAbHl1azk4LmNvbT7CiQQQFgoAMQQLCQcIAxUICgQWAAIBApsDAh4BFiEE
JwyxGxGJ55oX3LeDG9r9xdYOc1wFAmmyntYACgkQG9r9xdYOc1wM3gD/ftlK22Xw
hV4sWsHK3QaF7gg+Wjf6ktm5OCJHqCYJKWUBAKoIBkOunX+/qOQxOlVJE8trysV9
WZYn9jzcSeoRFe8GwowEEBYKAD4FgmSVACYECwkHCAmQG9r9xdYOc1wDFQgKBBYA
AgECGQECmwMCHgEWIQQnDLEbEYnnmhfct4Mb2v3F1g5zXAAA7WsA/2uyps4w7wTD
DZyxggbMS0mh3OCawLVB/3lxyxsuHQEWAP94CwjOlQv4/TMOp4POfYUGtH9gLrqT
ZPT+2gfv8Xa3DM0Z7J207JiB7JqxIDxwckBseXVrOTguY29tPsLBGAQTFgoBgAIb
AwQLCQgHBBUKCQgFFgIDAQACHgUCF4ACGQEWIQQnDLEbEYnnmhfct4Mb2v3F1g5z
XAUCabKmbTgUgAAAAAAQAB9wcm9vZkBhcmlhZG5lLmlkaHR0cHM6Ly9tYXN0b2Rv
bi5zb2NpYWwvQGx5dWs5OD8UgAAAAAAQACZwcm9vZkBhcmlhZG5lLmlkaHR0cHM6
Ly9naXRsYWIuY29tL2x5dWs5OC9naXRsYWJfcHJvb2YwFIAAAAAAEAAXcHJvb2ZA
YXJpYWRuZS5pZGRuczpseXVrOTguY29tP3R5cGU9VFhUQxSAAAAAABAAKnByb29m
QGFyaWFkbmUuaWRodHRwczovL2NvZGViZXJnLm9yZy9seXVrOTgva2V5b3hpZGVf
cHJvb2ZYFIAAAAAAEAA/cHJvb2ZAYXJpYWRuZS5pZGh0dHBzOi8vZ2lzdC5naXRo
dWIuY29tL2x5dWs5OC9iMTMzZGRjMGM1Y2Q1ZDgyYTRlYjY1MjZlNWY5ODMyOQAK
CRAb2v3F1g5zXHplAP9wqC2hBrsRlTKtqDQlXkrJOIu/Bg8ZU6fAV6Dlb+0iGQD/
V1qazc3M4YNKnICVgGGY35hdMvh2XYg0GuxXuXns8Q4=
=qt2L
-----END PGP PUBLIC KEY BLOCK-----
"""
