{
  imports = [
    ./disable-root.nix
    ./firmware.nix
    ./fonts.nix
    ./hardened.nix
    ./immutable-users.nix
    ./locale.nix
    ./msedit.nix
    ./nix.nix
    ./persistence.nix
    ./sops.nix
    ./sudo.nix
    ./systemd-initrd.nix
    ./systemd-resolved.nix
    ./tailscale.nix
    ./zram.nix
  ];
}
