{
  imports = [
    ./apparmor.nix
    ./bluetooth.nix
    ./disable-root.nix
    ./firmware.nix
    ./fonts.nix
    ./fprintd.nix
    ./hardened.nix
    ./immutable-users.nix
    ./locale.nix
    ./msedit.nix
    ./nix-topology.nix
    ./nix.nix
    ./preservation.nix
    ./run0.nix
    ./sops.nix
    ./systemd-initrd.nix
    ./systemd-resolved.nix
    ./tailscale.nix
    ./zram.nix
  ];
}
